### ISSUE TITLE
get byte[] from compressed int[]

### ISSUE THREAD

**Issue by rrphotosoft** [lemire/JavaFastPFOR#28]
Hi,
I'm new to java and this library in general.
I want to save the compressed int[] to redis.
The only way to do this is to first convert the int[] to a byte[].
Is there any way to get a byte[] array from the compressed int[] short of using ByteBuffer.
Thanks,
Rr.

**Comment by lemire** [comment]
If you want to convert int[] to byte[], this code should do the job :
http://stackoverflow.com/a/19252022/73007

If your arrays are small, this might do the job.

If your arrays are large (they do not fit in cache), a better alternative might be to use a ByteIntegerCODEC : 

http://lemire.me/docs/javafastpfor/me/lemire/integercompression/ByteIntegerCODEC.html

With this approach, you can compress an array of integers int[] directly to a byte array byte[].

There are currently only two : VariableByte and IntegratedVariableByte. They are both VByte schemes. There are reasonably fast.

**Comment by lemire** [comment]
I am closing this. Reopen if you disagree.

**Comment by rrphotosoft** [comment]
thank you so much. it works best with the codec.
I will be creating a ruby wrapper around your library.
I will drop you a message when its ready.
Regards,
Rr.

**Comment by lemire** [comment]
Great stuff.
