### ISSUE TITLE
ArrayIndexOutofBounds with SkippableComposition

### ISSUE THREAD

**Issue by akhld** [lemire/JavaFastPFOR#31]
Hi

Great work. I been playing with this lately and when i tried to random access the compressed values (using the SkippableComposition) its throwing up ArrayIndexOutOfBounds Exceptions.

This approach works fine:
       codec.headlessUncompress(compressed,inPoso, uncompressed.length, output, outPoso, i)

But when i tried to change the inPoso to read from a particular index, it throws up exception.

Eg:
        inPoso.set(i)
        codec.headlessUncompress(compressed,inPoso, uncompressed.length, output, outPoso, 1)

Am i doing something wrong here? Or is it like we cannot uncompress a particular element? Any help would be appreciated.

**Comment by lemire** [comment]
Can you provide a complete test?

It is difficult here to understand what is "i".

**Comment by akhld** [comment]
Hi Daniel,

thanks for reverting back. Here's a simple code snippet to reproduce it (its in scala, but you can easily understand it)

	    val uncompressed = Array(1,2,1,3,1)
	    println(uncompressed.toList)

	    var compressed = Array.ofDim[Int](uncompressed.length+1024)

	    val codec = new SkippableComposition(new BinaryPacking(), new VariableByte())

	    // compressing
	    val inPos = new IntWrapper()
	    val outPos = new IntWrapper()

	    codec.headlessCompress(uncompressed,inPos,uncompressed.length,compressed,outPos)

	    println("compressed unsorted integers from "+uncompressed.length*4/1024+"KB to "+outPos.intValue()*4/1024+"KB")

	    println(compressed.toList)


	    for(i<- 0 to 5){

	      val inPoso = new IntWrapper()

	      val outPoso = new IntWrapper()
	      var output = Array.ofDim[Int](uncompressed.length)

	      inPoso.set(i)

	      println("in => " + inPoso.get())

	      codec.headlessUncompress(compressed,inPoso, uncompressed.length, output, outPoso, i)

	      println(output(i) + " || " + output.toList)

	      println("out => " + outPoso.get())
	    }

![image](https://cloud.githubusercontent.com/assets/5821837/9567772/7f77e17e-4f54-11e5-9880-0cf9058c099b.png)

**Comment by lemire** [comment]
@akhld 
Thanks.

I have added an example that shows how headlessCompress and headlessUncompress are to be used. It is quite similar to the compress and uncompress methods, except that you need to know how many integers are stored in the array:

https://github.com/lemire/JavaFastPFOR/blob/master/example.java#L184-L222

There is currently no API call that would allow you to access individual values.

However, given a large array, you can segment it and decode just the subarray you need.

It would be possible to implement functions for random access to individual values, but that is not implemented yet. Moreover, in many applications, it might be more efficient to decompose your arrays in small blocks and uncompress small blocks.

So I am going to close this issue, as I do not think there is a bug here. If you have feature requests, please open an issue as such.

**Comment by akhld** [comment]
Cool Daniel thanks.

It would also be great to have a feature to access individual elements in the compressed stream. I will open a feature request.

**Comment by lemire** [comment]
> It would also be great to have a feature to access individual elements in the compressed stream. I will open a feature request.

It might in some instances, but it might also prove less useful than you think in other instances.

Repeatedly extracting single values can take orders of magnitude longer than if you just decode an array and access the values there. That's like trying to drink from a straw...

**Comment by akhld** [comment]
Makes sense. Let me try a bunch of exercises and see the performance. thanks a lot for the response.

**Comment by akhld** [comment]
Hi Daniel,

Just a follow-up question, not a question actually i need some insights/thoughts from you.

I'm building an In memory data store from scratch, so i take a text file (say csv), dictionary encode the column values (at this point i will have two data-structures, one for keeping the unique elements in the dictionary, and the other one an integer array which represents the actual encoded data). I'm using FastPFor to compress this integer array and the dictionary is compressed with GZip. I'm getting good compression ratio with these combinations. 

Now i need to query my data in such a way that it should take very less time to decompress it and lookup elements. I would need to know a bit about predicates here with FastPFor, is it good to support predicates with this combination (dictionary encode  + FastPFor)? If so, what is the best way to achieve this?

**Comment by lemire** [comment]
@akhld 

I am not sure what your exact question is, but the application you have in mind is well suited to FastPFor.
