### ISSUE TITLE
are codecs thread safe?

### ISSUE THREAD

**Issue by rrphotosoft** [lemire/JavaFastPFOR#32]
Hi,
I was just getting started with your library and was wondering, whether the a "codec" is thread safe? If I wanted to use this library in a web app, I was thinking of initializing the codec when my servlet initializes and then reusing it for different requests. 
Could you shed some light on this?
Regards,
RR.

**Comment by lemire** [comment]
The short answer is no: do not assume that they are thread-safe. For the longer answer:

https://github.com/lemire/JavaFastPFOR#thread-safery-

Thanks!
