### ISSUE TITLE
Comments suggest to perform diff encoding 

### ISSUE THREAD

**Issue by kk00ss** [lemire/JavaFastPFOR#34]
* Note that this does not use differential coding: if you are working on sorted
 * lists, you must compute the deltas separately. //From file OptPFD.java

Doing so increases the size of the output array from 58 to 104 integers.

```  val codecs = Array(
    new IntegratedComposition(new IntegratedBinaryPacking(),
      new IntegratedVariableByte()),
    new JustCopy(),
    new VariableByte(),
    new IntegratedVariableByte(),
    new Composition(new BinaryPacking(), new VariableByte()),
    new Composition(new NewPFD(), new VariableByte()),
    new Composition(new NewPFDS16(), new VariableByte()),
    new Composition(new OptPFD(), new VariableByte()),
    new Composition(new OptPFDS9(), new VariableByte()),
    new Composition(new OptPFDS16(), new VariableByte()),
    new Composition(new FastPFOR128(), new VariableByte()),
    new Composition(new FastPFOR(), new VariableByte()),
    new Simple9(),
    new Simple16(),
    new Composition(new XorBinaryPacking(), new VariableByte()),
    new Composition(new DeltaZigzagBinaryPacking(),
      new DeltaZigzagVariableByte()))

  def test2() = {
    val N = 100
    val r = new Random(System.nanoTime())
    val keys = (1 to N).map(i => {
      //r.nextInt(Int.MaxValue)
      i*Short.MaxValue*2+r.nextInt(Short.MaxValue*2)
    }).toArray
    println(keys.toList)
    println(s"size before compression ${keys.size}")
    codecs.foreach(codec => {
      print(s"${codec.toString} , ")
      val iic = new IntegratedIntCompressor()
      var start = System.nanoTime()
      val keys2 =  diffEncoder.compress(keys)
      val compressed = iic.compress(keys2) // compressed array
      val encodeTime = System.nanoTime() - start
      print(s" $encodeTime , ")
      print(s" ${compressed.size} , ")
      start = System.nanoTime()
      val recov = iic.uncompress(compressed)
      //val reKeys = diffEncoder.decompress(recov)
      val decodeTime = System.nanoTime() - start
      println(s" $decodeTime , ")
      //println("reKeys == keys  "+(reKeys.toList==keys.toList))
      //println("reKeys == keys  "+(reKeys==keys))

      //println(compressed.toList)
    })
    }

  object diffEncoder{
    def compress(in:Array[Int]):Array[Int]={
      val in1 = new Array[Int](in.length)
      var i = 0
      while(i < in.length){
        if(i == 0)
          in1(i) = in(i)
        else {
          in1(i) = in(i) - in(i-1)
        }
        i +=1
      }
      return in1
    }

    def decompress(in:Array[Int]):Array[Int]={
      val in1 = new Array[Int](in.length)
      var i = 0
      while(i < in.length){
        if(i == 0)
          in1(i) = in(i)
        else {
          in1(i) = in(i) + in1(i-1)
        }
        i +=1
      }
      return in1
    }
  }```

**Comment by kk00ss** [comment]
Also could you please comment on another issue, why compressed array size for a number of codecs is exactly the same ?

**Comment by lemire** [comment]
If differential coding increases the compressed size, then do not use differential coding. There is nothing in the library saying that using differential coding will improve compression in all instances. The documentation you are quoting is a usage hint.

The fact that compressed size is the same for several codecs is also not an issue. There is nothing in the library saying that the compressed size has to vary from codec to codec.

**Comment by kk00ss** [comment]
My problem is it the same even for JustCopy, which I believe should be the
original one.

2015-12-09 22:10 GMT+02:00 Daniel Lemire <notifications@github.com>:

**Comment by lemire** [comment]
@kk00ss 

> My problem is it the same even for JustCopy, which I believe should be the
original one.

Here is the source code of JustCopy.java that you can examine: 

https://github.com/lemire/JavaFastPFOR/blob/master/src/main/java/me/lemire/integercompression/JustCopy.java

It is a wrapper around System.arraycopy. 

If you have spotted a bug in JustCopy, please provide a reproduce test case. Please provide your test case in Java.

**Comment by kk00ss** [comment]
Sorry for bothering you - there is a bug in my code. Thanks for a great
library.

2015-12-09 22:27 GMT+02:00 Daniel Lemire <notifications@github.com>:
