### ISSUE TITLE
Decompression requires length of original array

### ISSUE THREAD

**Issue by tenstriker** [lemire/JavaFastPFOR#35]
Hi, first of all thank you for this cool library. I was looking at example.java and particular into basicExample() method to compress sorted integer array. I find that decompression requires buffer of length equal to original array. While I can store that length value as a first or last element of compressed array but that will add some overhead to both compression and decompression. Is it possible to use dynamic construct like list or seq as buffer when decompressing?

**Comment by lemire** [comment]
Thank you. 

> While I can store that length value as a first or last element of compressed array but that will add some overhead to both compression and decompression.

True. I recommend you should use the SkippableIntegerCODEC interface *and* store the number of compressed values elsewhere. In this manner, there will be no extra overhead....

http://static.javadoc.io/me.lemire.integercompression/JavaFastPFOR/0.1.6/me/lemire/integercompression/SkippableIntegerCODEC.html

**Comment by lemire** [comment]
For example, see 
https://github.com/lemire/JavaFastPFOR/blob/master/example.java#L88-L146
