### ISSUE TITLE
changing BLOCK_SIZE?

### ISSUE THREAD

**Issue by kodonnell** [lemire/JavaFastPFOR#38]
Refering to [here](https://github.com/lemire/JavaFastPFOR/blob/master/src/main/java/me/lemire/integercompression/FastPFOR.java#L16-L17) - is this suggesting increasing BLOCK_SIZE, and, if so, how does one do that? I can't appear to overwrite/extend it (though I'm not a pro at such things).

**Comment by lemire** [comment]
No, it is not suggesting to increase BLOCK_SIZE. It is saying that you will get best results if you try to compress sizeable arrays. This CODEC will not work on arrays containing few integers.

**Comment by kodonnell** [comment]
Thanks - maybe a change in the comment might make this a little clearer. (I.e. 'sizeable blocks' made me think of 'block size'.)

**Comment by lemire** [comment]
https://github.com/lemire/JavaFastPFOR/commit/5846d86f72b1fb6bb97b7f8e405892e13095c497
