### ISSUE TITLE
Integrated Composition not working properly with output offset != 0

### ISSUE THREAD

**Issue by borisshou** [lemire/JavaFastPFOR#41]
I encountered the same issue as #29 , except that I was using Integrated Composition instead of just Composition. To reproduce the error, consider the following code:

```
int x = 0;
SkippableIntegratedIntegerCODEC sortedCodec = new SkippableIntegratedComposition(
        new IntegratedBinaryPacking(), new IntegratedVariableByte());

int[] original = new int[] {1};
int[] compressed = new int[10];
IntWrapper outputOffset = new IntWrapper(x);
sortedCodec.headlessCompress(original, new IntWrapper(0), original.length, compressed, outputOffset, new IntWrapper(0));
System.out.println(Arrays.toString(compressed));
```
The output is `[0, 129, 0, 0, 0, 0, 0, 0, 0, 0]`, meaning that `[0]` has been compressed into `[0, 129]`. However, if we change the first line to `x = 1`, the output is still `[0, 129, 0, 0, 0, 0, 0, 0, 0, 0]`, meaning that this time `[0]` has been compressed into `[129]` instead. 

A quick hack to fix the issue would be to switch the order of the two arguments being passed into `SkippableIntegratedComposition()`, but further experiments suggested that this would decrease performance.

Would you mind looking into this issue? Thanks!

**Comment by lemire** [comment]
We’ll have a look.

**Comment by lemire** [comment]
Fixed in release 0.1.12. It should now work as you expect. Please reopen if you still have troubles.

**Comment by borisshou** [comment]
Thanks for fixing it so quickly! I just verified that it is working now.

**Comment by lemire** [comment]
Great.
