### ISSUE TITLE
If JavaFastPFOR can have list/set as parameters

### ISSUE THREAD

**Issue by lei-hsia** [lemire/JavaFastPFOR#48]
It seems as if only type `int[] data` can be passed as parameters now. Many times people would use Collections such as List/Set though, especially for large amount of data transmission/streaming/IO. 

I wonder if there are APIs taking `List`/`Set` as parameters.

**Comment by lemire** [comment]
You can convert your data structures to arrays easily:
```Java
int[] array = list.stream().mapToInt(i->i).toArray();
```

and then call the appropriate methods.

If you have more sophisticated/efficient ideas, please consider creating a pull request so we can discuss the issue with code samples.
