### ISSUE TITLE
Decompress using pyfastpfor

### ISSUE THREAD

**Issue by swapnilnawale** [lemire/JavaFastPFOR#49]
Can one use pyfastpfor to decompress the arrays compressed using  JavaFastPFOR? Specifically looking for the following compression schemes:
```        
val codec = SkippableIntegratedComposition(
            IntegratedBinaryPacking(),
            IntegratedVariableByte()
        )
```

and 

```
 val codec = SkippableComposition(
            BinaryPacking(),
            VariableByte()
        )
```

**Comment by lemire** [comment]
Not to my knowledge.

If you need this feature, it should be possible to build it up, but it is possible that you might need to do some software work and add some additional tests. 

Pull request invited!
