### ISSUE TITLE
A Vector Implementation of JavaFastPFOR

### ISSUE THREAD

**Issue by mulugetam** [lemire/JavaFastPFOR#50]
We have implemented a vectorized version of JavaFastPFOR. Based on our benchmark results, it has significant gains over the default, non-vectorized, FastPFOR. The source code and the JMH benchmark results are [here](https://github.com/mulugetam/VectorJavaFastPFOR).

We'd like to do a PR to this repo but aren't sure how to proceed. Your code doesn't use modules and we also rely on Java's Vector API (which our team is a major contributor to). Please let us know what you think. 

Thanks

**Comment by lemire** [comment]
We could switch JavaFastPFOR over to modules ?

**Comment by mulugetam** [comment]
Have done the PR.

**Comment by lemire** [comment]
Closing.
